GET http://localhost:3000/api/pokemons/

###

GET http://localhost:3000/api/pokemons/b07c82d0-0901-11ec-9057-83595f40ff2c



###
POST http://localhost:3000/api/pokemons
Content-Type: application/json

{
		"specie": "Pikachu",
		"height": 12,
		"description":
			"Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy. When it smashes its opponents with its bolt- shaped tail, it delivers a surge of electricity equivalent to a lightning strike. Its Gigantamax power expanded, forming its supersized body and towering tail.",
		"hp": 190
}

### 
PUT http://localhost:3000/api/pokemons/b07c82d0-0901-11ec-9057-83595f40ff2c
Content-Type: application/json

{
		"specie": "Pikachuu",
		"height": 12,
		"description":
			"Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy. When it smashes its opponents with its bolt- shaped tail, it delivers a surge of electricity equivalent to a lightning strike. Its Gigantamax power expanded, forming its supersized body and towering tail.",
		"hp": 190

}

###
DELETE http://localhost:3000/api/pokemons/b07c82d0-0901-11ec-9057-83595f40ff2c