GET http://localhost:3000/api/pokemons/

###

GET http://localhost:3000/api/pokemons/64134040-06a0-11ec-98a1-29bfeb9ee5f9


###
POST http://localhost:3000/api/pokemons
Content-Type: application/json

{
		"specie": "raderas",
		"height": 2,
		"description":
			"Venusaur is a Grass/Poison type Pokémon introduced in Generation 1. It is known as the Seed Pokémon.\nVenusaur has a Mega Evolution, available from X & Y onwards.",
		"hp": 80 
}

### 
PUT http://localhost:3000/api/pokemons/
Content-Type: application/json

{
		"specie": "emina",
		"height": 1222,
		"description":
			"Venusaur nVenusaur has a Mega Evolution, available from X & Y onwards.",
		"hp": 10

}

###
DELETE http://localhost:3000/api/pokemons/637fd9e0-06a0-11ec-806e-d3f285f9f859